export const ERROR_CODES = {
    INVALID_REQUEST: 'INVALID_REQUEST',
    SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
    MCP_ERROR: 'MCP_ERROR',
    TOOL_NOT_FOUND: 'TOOL_NOT_FOUND',
    TOOL_VALIDATION_ERROR: 'TOOL_VALIDATION_ERROR',
    CORS_ERROR: 'CORS_ERROR',
    TIMEOUT: 'TIMEOUT',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
};

export const HTTP_STATUS = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_ERROR: 500,
    BAD_GATEWAY: 502,
    GATEWAY_TIMEOUT: 504
};

export const TIMEOUTS = {
    MCP_CALL: 30000,
    SESSION_EXPIRY: 3600000
};
